### ISSUE TITLE
Tag Reviewer on Slack

### ISSUE THREAD

**Issue by johnallen3d** [iamvery/lita-reviewme#43]
What if when a reviewer is assigned they were also tagged in the Slack response? Something like this:

```
foo should be on it... /cc @foo.bar
```

Some on my team are not getting Github notifications (for shame!) and everybody loves Slack.

This would require an optional second parameter to `#add_reviewer` and additional logic for `response.reply("#{reviewer} should be on it...")`.

I'd be happy to work up a PR if this sounds desirable to others.

**Comment by johnallen3d** [comment]
Well, one of my team members has a much simpler suggestion. If you set up your github username (assuming it's different from Slack handle) as a [highlight word](https://get.slack.help/hc/en-us/articles/201398467-Highlight-word-notifications) in slack you'll get notified! Perhaps a note/suggestion to add to the README?

I'll go ahead and close this. Sorry for the noise.

**Comment by iamvery** [comment]
Hah, that's exactly what I'm doing as well! We have had in mind to connect Slack and GH users in some way to streamline this, but it hasn't gotten attention yet. I like the idea of adding something to the readme.

**Comment by iamvery** [comment]
What do you think about :arrow_heading_up:? Since lita is agnostic of chat platform, I didn't want to say anything specific to Slack. Legit?

**Comment by johnallen3d** [comment]
:+1: I'm having a hard time remembering the fact that not all users are on Slack at this point! :wink:

**Comment by iamvery** [comment]
Yeah, it's actually somewhat confusing when developing lita plugins. Because it's gotten quite ubiquitous :)
