### ISSUE TITLE
Bot should not comment when no reviewer is selected

### ISSUE THREAD

**Issue by jeremy-w** [iamvery/lita-reviewme#44]
I did a `review <URL>` command in a room where no reviewers were registered.

My PR now has an ":eyes @" comment with no username.

Having it explain "yeah you need to add reviewers for this room first" would probably be a good move.

**Comment by jeremy-w** [comment]
See also #35. Looks like now it does respond.

**Comment by iamvery** [comment]
:+1:

**Comment by binarymason** [comment]
This is fixed as of https://github.com/iamvery/lita-reviewme/pull/51

**Comment by iamvery** [comment]
❤️
