### ISSUE TITLE
skip author from being assigned reviewer

### ISSUE THREAD

**Issue by MarkVaughn** [iamvery/lita-reviewme#46]
More often then not in a group of 7 reviewers the author of a PR is assigned as reviewer when calling the bot. Would be nice if in that case it switched places with the next user.

Thanks for this cool plugin!

**Comment by iamvery** [comment]
Hurray! So glad you have found this useful. I recently merged [a PR](https://github.com/iamvery/lita-reviewme/pull/36) that prevents assignment to the creator of a PR, but it still doesn't account for self-assignment when just asking for a reviewer (outside of github).

When I get some time, I'd like to have a separate lita handler that allows you to manage user metadata (including github username) in your lita user record. Then reviewme could use that to prevent self-assignment and such. I talked a little about that [here](https://github.com/iamvery/lita-reviewme/pull/45#issuecomment-195478436).

Does that make sense? Does it answer your question? Thanks for the encouragement! :heart:
