### ISSUE TITLE
New Feature: Allow GitHub comment injection

### ISSUE THREAD

**Issue by binarymason** [iamvery/lita-reviewme#49]
Came across a need to customize the [github_comment](https://github.com/iamvery/lita-reviewme/blob/master/lib/lita/handlers/reviewme.rb#L122-L124) method today.

```ruby
def github_comment(reviewer)
  ":eyes: @#{reviewer}"
end
```

Do you guys have any opinions on allowing custom GitHub messages? Maybe default to the 👀 message unless something is injected?

```ruby
def github_comment(reviewer, msg = nil)
  msg || ":eyes: @#{reviewer}"
end
```

**Comment by iamvery** [comment]
Sounds like a great addition! You could do something with the [String format operator `%`](http://ruby-doc.org/core-2.4.0/String.html#method-i-25) to give it a template-like quality. Also, probably use the Lita config to specify the format:

```ruby
# your bot's lita_config.rb
config.handlers.reviewme.github_comment_template = ":eyes: %{reviewer}"

# in reviewme.rb
def github_comment(reviewer)
  config.github_comment_template % reviewer
end
```

What do you think? Thanks for the great idea! ❤️

**Comment by binarymason** [comment]
LGTM.  👍  I'll open a PR.

**Comment by iamvery** [comment]
See #50
