### ISSUE TITLE
Github assignment fails for URL with anchor

### ISSUE THREAD

**Issue by iamvery** [iamvery/lita-reviewme#60]
e.g.

```
me: bot review https://github.com/some/thing/pull/188#pullrequestreview-1234
bot: Unable to check who issued the pull request. Sorry if you end up being assigned your own PR!
```

**Comment by davidsawyer** [comment]
This might have fixed itself. I can't seem to reproduce this issue.

**Comment by iamvery** [comment]
Thanks for letting me know! I wonder if this was an issue with the github library? Regardless, it seems reasonable to close this out until we hit it again.

(sorry the delayed response on these. i appreciate your jumping in! ❤️)
